apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: lide-aa-course
spec:
  # build:
    # secrets:
    #   - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "78afa1ba-a88a-4efc-a40c-9fc1bc6d7297"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET